package com.sebastianfox.food.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.sebastianfox.food.models.LabelText;
import com.sebastianfox.food.repository.Label.LabelRepository;
import org.json.JSONException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import java.io.IOException;
import java.util.HashMap;

@SuppressWarnings("Duplicates")
@Controller    // This means that this class is a Controller
@RequestMapping(path = "/api/label") // This means URL's start with /api (after Application path)
public class LabelController {

    private final LabelRepository labelRepository;


    // This means to get the bean called labelRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    @Autowired
    public LabelController(LabelRepository labelRepository) {
        this.labelRepository = labelRepository;
    }

    /**
     *
     * @param localeData JSON data from App
     * @return http response
     * @throws JSONException exception
     * @throws IOException exception
     */
    @RequestMapping(path = "/loadLabels", method = RequestMethod.POST, consumes = {"application/json"})
    public ResponseEntity<Object> authenticate(@RequestBody HashMap<String, String> localeData) throws JSONException, IOException {

        Iterable<LabelText> labels = labelRepository.findAll();
        for (LabelText labelText : labels) {
            labelText.setTextByLanguage(localeData.get("locale"));
        }

        ObjectMapper mapper = new ObjectMapper();
        HashMap<String,Object> hashMap = new HashMap<>();

        // Successful login
        hashMap.put("status","success");
        hashMap.put("labels",labels);
        // Object to JSON String
        String jsonString = mapper.writeValueAsString(hashMap);
        // Return to App
        return new ResponseEntity<>(jsonString, HttpStatus.ACCEPTED);
    }
}
